-- 코드를 입력하세요
SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME AS PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) FO
JOIN FOOD_PRODUCT FP
ON FO.PRODUCT_ID = FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;